name: CustomAction1
on:
  workflow_dispatch:
jobs:
  validate-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get the last commit
        id: last-commit
        run: echo "message=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Run tests
        run: |
          cd .github/actions/validate-commit
          npm install

      - name: Validate the commit message
        uses: ./.github/actions/validate-commit
        with:
          commit_message: ${{ env.message }}
            