name: Needs
on:
  workflow_dispatch:
jobs:
  primer-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo en el primer job
        run: echo "Este es el primer job"
  segundo-job:
    runs-on: ubuntu-latest
    needs: primer-job
    steps:
      - name: Echo en el segundo job
        run: echo "Este es el segundo job"
        
